[tool.poetry]
name = "maidr"
version = "0.1.0"
description = "Multimodal Access and Interactive Data Representations"
authors = ["JooYoung Seo <jseo1005@illinois.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.7.1"
numpy = "^1.24.3"
seaborn = "^0.12.2"
lxml = "^4.9.2"


[tool.poetry.group.dev.dependencies]
black = "23.3.0"
sphinx = "^7.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
